// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-CgMNXrMKlJ9Pa6ccHeajBo7XsRy04Kc',
    appId: '1:235068923831:web:5d27be65a1a746e87c1232',
    messagingSenderId: '235068923831',
    projectId: 'e-commerceapp-c922a',
    authDomain: 'e-commerceapp-c922a.firebaseapp.com',
    storageBucket: 'e-commerceapp-c922a.appspot.com',
    measurementId: 'G-YZK6N9R010',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBGOeZInj3-XtpN62UAAeXVcVBGlZrvrI',
    appId: '1:235068923831:android:5854e8baaa57bfff7c1232',
    messagingSenderId: '235068923831',
    projectId: 'e-commerceapp-c922a',
    storageBucket: 'e-commerceapp-c922a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM3CFZIE-fyLJV8dxxGYNCO9m1ybioIEE',
    appId: '1:235068923831:ios:ef3b74b86d30ff327c1232',
    messagingSenderId: '235068923831',
    projectId: 'e-commerceapp-c922a',
    storageBucket: 'e-commerceapp-c922a.appspot.com',
    androidClientId: '235068923831-dngh3l8btc7rd5nlps1n77tnk707d0h8.apps.googleusercontent.com',
    iosClientId: '235068923831-8rulsjekmfvu04jqq7avcl760r128ph7.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM3CFZIE-fyLJV8dxxGYNCO9m1ybioIEE',
    appId: '1:235068923831:ios:c2da46ed273685617c1232',
    messagingSenderId: '235068923831',
    projectId: 'e-commerceapp-c922a',
    storageBucket: 'e-commerceapp-c922a.appspot.com',
    androidClientId: '235068923831-dngh3l8btc7rd5nlps1n77tnk707d0h8.apps.googleusercontent.com',
    iosClientId: '235068923831-arljhn2j6ja4dj7281ulsbtc6kr0p59c.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
